TRAIN:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/slowfast/projects/rev/REV_MVIT_B_16x4.pyth
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: True

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5 # [1, 3, 5, 7, 10]
  CHECKPOINT_TYPE: pytorch
  SAVE_RESULTS_PATH: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/revmvit-kabr-kinetics/results.txt"
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/revmvit-kabr-kinetics/checkpoints/checkpoint_epoch_00120.pyth

DATA:
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 4
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  PATH_TO_DATA_DIR: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation"
  PATH_PREFIX: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/dataset/image"
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]

MVIT:
  ZERO_DECAY_POS_CLS: False
  CLS_EMBED_ON: False # todo: changed from True to False
  SEP_POS_EMBED: True
  USE_ABS_POS: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: False
  DROPPATH_RATE: 0.05
  NORM: "layernorm"
  MODE: "conv"
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]

  REV:
    ENABLE: True
    RESPATH_FUSE: "concat"
    BUFFER_LAYERS : [1, 3, 14]
    RES_PATH : "conv"

AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1 # todo: changed from 2 to 1
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False

MIXUP:
  ENABLE: True
  ALPHA: 0.8
  LABEL_SMOOTH_VALUE: 0.1
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5

SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR:  1e-6
  MAX_EPOCH: 120
  WARMUP_EPOCHS: 30.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 7e-2
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR: 0.000001
  OPTIMIZING_METHOD: adamw

MODEL:
  NUM_CLASSES: 8
  ARCH: slow
  MODEL_NAME: MViT
  LOSS_FUNC: EQL
  DROPOUT_RATE: 0.5


DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/revmvit-kabr-kinetics


TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  HISTOGRAM:
    ENABLE: True
    TOPK: 3
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  MODEL_VIS:
    ENABLE: False
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    LAYER_LIST: ['s5/pathway0_res14']
    GRAD_CAM:
      ENABLE: False
      LAYER_LIST: ['s5/pathway0_res14']

DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/KABR/annotation/classes.json
  # INPUT_VIDEO: # path to input
  # OUTPUT_FILE: # path to output
  THREAD_ENABLE: False
  THREAD_ENABLE: False
  NUM_VIS_INSTANCES: 1
  NUM_CLIPS_SKIP: 1