TRAIN:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/slowfast/projects/slowfast/checkpoint_epoch_00070.pyth
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: True

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
  SAVE_RESULTS_PATH: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/slowfast-kabr-ak/results.txt"
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/slowfast-kabr-ak/checkpoints/checkpoint_epoch_00120.pyth
  CHECKPOINT_TYPE: pytorch

DATA:
  NUM_FRAMES: 64
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 340]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation"
  PATH_PREFIX: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/dataset/image"
  
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
  
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1

SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 41, 49]
  MAX_EPOCH: 120
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 4.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 8
  ARCH: slowfast
  LOSS_FUNC: EQL
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5



DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/slowfast-kabr-ak
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: False

TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  HISTOGRAM:
    ENABLE: True
    TOPK: 3
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  MODEL_VIS:
    ENABLE: False
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    LAYER_LIST: ['s5/pathway0_res14']
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway0_res14']


DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /mnt/HDD/Backup/Animal Action Recognition/Animal_Kingdom/annotation/classes.json
  # INPUT_VIDEO: /mnt/HDD/Backup/Animal Action Recognition/Animal_Kingdom/dataset/video/ADDOKUJL.mp4
  INPUT_VIDEO: /mnt/HDD/Backup/Animal Action Recognition/Animal_Kingdom/dataset/video/AAUVWMRN.mp4
#  INPUT_VIDEO: /mnt/HDD/Backup/Animal Action Recognition/baboons/tracks/GH020158/br.mp4
  OUTPUT_FILE: /mnt/HDD/Backup/Animal Action Recognition/Animal_Kingdom/video.mp4
  THREAD_ENABLE: False
  NUM_VIS_INSTANCES: 1
  NUM_CLIPS_SKIP: 1
  COMMON_CLASS_THRES: 0.5
  UNCOMMON_CLASS_THRES: 0.3
  COMMON_CLASS_NAMES: []