TRAIN:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH:
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: False
  MIXED_PRECISION: True

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 1
  # CHECKPOINT_FILE_PATH:
  CHECKPOINT_TYPE: pytorch

DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [300, 300]
  TRAIN_CROP_SIZE: 300
  TEST_CROP_SIZE: 300
  TRAIN_CROP_NUM_TEMPORAL: 1
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: False
  RANDOM_FLIP: True
  SSL_COLOR_JITTER: True
  SSL_COLOR_BRI_CON_SAT: [0.2, 0.2, 0.2]
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: "./KABR/annotation"
  PATH_PREFIX: "./KABR/dataset/image"
  DECODING_BACKEND: torchvision

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.05
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 120
  LR_POLICY: cosine
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 8
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./logs/x3d-l-kabr
LOG_MODEL_INFO: True

TENSORBOARD:
  ENABLE: False

DEMO:
  ENABLE: True
  LABEL_FILE_PATH: ./KABR/annotation/classes.json
  # INPUT_VIDEO: # path to input
  # OUTPUT_FILE: # path to output
  THREAD_ENABLE: False
  THREAD_ENABLE: False
  NUM_VIS_INSTANCES: 1
  NUM_CLIPS_SKIP: 1