TRAIN:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/animal_kingdom/logs/x3d-l-lr5e-2-ep100/checkpoints/checkpoint_epoch_00100.pyth
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: True

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_TYPE: pytorch
  SAVE_RESULTS_PATH: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/x3d-l-kabr-kinetics-lr5e-2-ep120-ak/results.txt"
  CHECKPOINT_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/x3d-l-kabr-kinetics-lr5e-2-ep120-ak/checkpoints/checkpoint_epoch_00120.pyth

DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [300, 400]
  TRAIN_CROP_SIZE: 300
  TEST_CROP_SIZE: 300
  TRAIN_CROP_NUM_TEMPORAL: 1
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  RANDOM_FLIP: True
  SSL_COLOR_JITTER: True
  SSL_COLOR_BRI_CON_SAT: [0.2, 0.2, 0.2]
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation"
  PATH_PREFIX: "/jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/dataset/image"
  DECODING_BACKEND: torchvision

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.05
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 120
  LR_POLICY: cosine
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 8
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: EQL
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/logs/x3d-l-kabr-kinetics-lr5e-2-ep120-ak
LOG_MODEL_INFO: True

TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  HISTOGRAM:
    ENABLE: True
    TOPK: 3
    SUBSET_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.txt
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False
    ACTIVATIONS: False
    INPUT_VIDEO: False
    LAYER_LIST: ['s5/pathway0_res14']
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway0_res14']

DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/annotation/classes.json
  INPUT_VIDEO: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/dataset/video/G0103.mp4
  OUTPUT_FILE: /jmain02/home/J2AD001/wwp02/mxk71-wwp02/uob_project/kabr/KABR/dataset/predict/G0103.mp4
  THREAD_ENABLE: False
  THREAD_ENABLE: False
  NUM_VIS_INSTANCES: 1
  NUM_CLIPS_SKIP: 1
  # VIS_MODE: "top-k"
  # UNCOMMON_CLASS_THRES: 0.3
  # COMMON_CLASS_THRES: 0.7
  # COMMON_CLASS_NAMES: ["Graze"]